name: Executar dados.py

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Run Python Script
        run: |
          python -m pip install requests
          python scripts/dados.py
          
      - name: Adicionar alterações ao Git
        run: git add .

      - name: Confirmar alterações
        run: git commit -m "Atualizações automáticas"

      - name: Fazer push das alterações
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
